import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { Observable } from 'rxjs';

import { SeoService } from '../../../../core/services/seo.service';
import { messageForError } from '../../../../shared/util/api-error.util';
import { AdminWeeklySummaryApiService } from '../../services/admin-weekly-summary-api.service';
import { AdminPaginationComponent } from '../../components/admin-pagination.component';
import {
  WEEKLY_SUMMARY_STATUSES,
  WeeklySummaryListItem,
  WeeklySummaryPage,
  WeeklySummaryStatus
} from '../../models/weekly-summary.models';
import { formatDate, formatTimestamp, statusBadgeClass } from '../../util/admin-format.util';

type View = 'loading' | 'ready';

@Component({
  selector: 'fx-admin-weekly-recap',
  standalone: true,
  imports: [FormsModule, RouterLink, AdminPaginationComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <h1 class="font-display text-2xl font-bold text-navy-900">Weekly Recaps</h1>

    @if (banner(); as msg) {
      <p class="mt-4 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{{ msg }}</p>
    }
    @if (notice(); as msg) {
      <p class="mt-4 rounded-lg bg-green-50 px-3 py-2 text-sm text-green-700">{{ msg }}</p>
    }

    <label class="mt-6 block sm:w-48">
      <span class="text-xs font-semibold uppercase tracking-wide text-navy-400">Status</span>
      <select
        [(ngModel)]="status"
        (ngModelChange)="applyFilters()"
        class="mt-1 w-full rounded-lg border border-surface-border bg-white px-3 py-2 text-sm text-navy-900 outline-none transition focus:border-accent focus:ring-1 focus:ring-accent"
      >
        <option [ngValue]="undefined">All statuses</option>
        @for (s of statuses; track s) {
          <option [ngValue]="s">{{ s }}</option>
        }
      </select>
    </label>

    @if (view() === 'loading') {
      <div class="mt-6 h-64 animate-pulse rounded-2xl bg-white"></div>
    }

    @if (view() === 'ready' && page(); as pg) {
      @if (!pg.items.length) {
        <div class="mt-6 rounded-2xl border border-surface-border bg-white p-8 text-center">
          <p class="text-sm font-semibold text-navy-900">No weekly recaps</p>
          <p class="mt-1 text-sm text-navy-500">Drafts are generated by the backend each week.</p>
        </div>
      } @else {
        <div class="mt-6 overflow-x-auto rounded-2xl border border-surface-border bg-white">
          <table class="w-full min-w-[760px] text-left text-sm">
            <thead class="border-b border-surface-border bg-surface-muted text-xs font-semibold uppercase tracking-wide text-navy-500">
              <tr>
                <th class="px-4 py-3">Week</th>
                <th class="px-4 py-3">Title</th>
                <th class="px-4 py-3">Status</th>
                <th class="px-4 py-3">Published</th>
                <th class="px-4 py-3"></th>
              </tr>
            </thead>
            <tbody>
              @for (w of pg.items; track w.id) {
                <tr class="border-b border-surface-border last:border-0 align-top">
                  <td class="whitespace-nowrap px-4 py-3 text-navy-700">
                    {{ formatDate(w.weekStart) }} – {{ formatDate(w.weekEnd) }}
                  </td>
                  <td class="px-4 py-3 text-navy-800">
                    <div class="font-medium">{{ w.title }}</div>
                    <div class="text-xs text-navy-400">/{{ w.slug }}</div>
                  </td>
                  <td class="px-4 py-3">
                    <span class="rounded-full px-2 py-0.5 text-xs font-semibold" [class]="badge(w.status)">
                      {{ w.status }}
                    </span>
                  </td>
                  <td class="whitespace-nowrap px-4 py-3 text-navy-600">{{ formatTimestamp(w.publishedAt) }}</td>
                  <td class="whitespace-nowrap px-4 py-3 text-right">
                    <div class="flex flex-wrap justify-end gap-2">
                      <a
                        [routerLink]="['/admin/weekly-recap', w.id]"
                        class="rounded-lg border border-surface-border px-3 py-1.5 text-xs font-semibold text-navy-700 transition hover:bg-surface-muted"
                      >
                        Review
                      </a>
                      @if (w.status !== 'PUBLISHED') {
                        <button
                          type="button"
                          [disabled]="busyId() === w.id"
                          (click)="publish(w)"
                          class="rounded-lg border border-surface-border px-3 py-1.5 text-xs font-semibold text-green-700 transition hover:bg-green-50 disabled:opacity-50"
                        >
                          Publish
                        </button>
                      }
                      @if (w.status !== 'ARCHIVED') {
                        <button
                          type="button"
                          [disabled]="busyId() === w.id"
                          (click)="archive(w)"
                          class="rounded-lg border border-surface-border px-3 py-1.5 text-xs font-semibold text-navy-600 transition hover:bg-surface-muted disabled:opacity-50"
                        >
                          Archive
                        </button>
                      }
                    </div>
                  </td>
                </tr>
              }
            </tbody>
          </table>
        </div>

        <fx-admin-pagination [page]="pg.page" [totalPages]="pg.totalPages" (change)="goTo($event)" />
      }
    }
  `
})
export class AdminWeeklyRecapComponent {
  private readonly api = inject(AdminWeeklySummaryApiService);

  readonly view = signal<View>('loading');
  readonly page = signal<WeeklySummaryPage | null>(null);
  readonly banner = signal('');
  readonly notice = signal('');
  readonly busyId = signal<number | null>(null);

  readonly statuses = WEEKLY_SUMMARY_STATUSES;
  readonly formatDate = formatDate;
  readonly formatTimestamp = formatTimestamp;

  status?: WeeklySummaryStatus;

  constructor() {
    inject(SeoService).apply({ title: 'Weekly Recaps' });
    this.load(1);
  }

  private load(page: number): void {
    this.view.set('loading');
    this.api.list({ page, status: this.status }).subscribe({
      next: (pg) => {
        this.page.set(pg);
        this.view.set('ready');
      },
      error: (err) => {
        this.banner.set(messageForError(err));
        this.view.set('ready');
      }
    });
  }

  applyFilters(): void {
    this.banner.set('');
    this.notice.set('');
    this.load(1);
  }

  goTo(page: number): void {
    if (page < 1) {
      return;
    }
    this.load(page);
  }

  badge(status: WeeklySummaryStatus): string {
    return statusBadgeClass(status);
  }

  publish(w: WeeklySummaryListItem): void {
    this.run(w.id, this.api.publish(w.id), 'Recap published.');
  }

  archive(w: WeeklySummaryListItem): void {
    this.run(w.id, this.api.archive(w.id), 'Recap archived.');
  }

  private run(id: number, call: Observable<unknown>, success: string): void {
    this.notice.set('');
    this.banner.set('');
    this.busyId.set(id);
    call.subscribe({
      next: () => {
        this.busyId.set(null);
        this.notice.set(success);
        this.load(this.page()?.page ?? 1);
      },
      error: (err: unknown) => {
        this.busyId.set(null);
        this.banner.set(messageForError(err));
      }
    });
  }
}
