export const APP_ROUTES = {
  landing: '/',
  login: '/login',
  register: '/register',
  verifyEmail: '/verify-email',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  oauthCallback: '/oauth/callback',
  about: '/about',
  privacy: '/privacy',
  terms: '/terms',
  support: '/support',
  forbidden: '/forbidden',
  error: '/error',
  dashboard: '/dashboard',
  history: '/history',
  account: '/account',
  adminDashboard: '/admin',
  adminUsers: '/admin/users',
  adminUsage: '/admin/usage',
  adminFeedback: '/admin/feedback'
} as const;
